release:
  name_template: '{{.Version}} / {{time "2006-01-02"}}'
  prerelease: auto
  mode: append
  footer: |
    ## Docker Image
    Use the following command to pull this release's Docker image:
    ```sh
    docker pull redpandadata/kminion:{{ .Tag }}
    ```
changelog:
  skip: false
  use: github
  filters:
    # Commit messages matching the regexp listed here will be removed from the changelog
    exclude:
      - '^docs:'
      - '^test:'
      - '^npm:'
      - '^go.mod:'
      - '^.github:'
      - 'Merge branch'

builds:
  - id: kminion
    binary: kminion
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.builtAt={{.Date}} -X main.commit={{.Commit}}

checksum:
  name_template: 'checksums.txt'
